all:
	$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build"
kissat:
	$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build" kissat
tissat:
	$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build" tissat
clean:
	rm -f "/home/porrasm/school/alr_2021/kissat"/makefile
	-$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build" clean
	rm -rf "/home/porrasm/school/alr_2021/kissat/build"
coverage:
	$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build" coverage
indent:
	$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build" indent
test:
	$(MAKE) -C "/home/porrasm/school/alr_2021/kissat/build" test
.PHONY: all clean coverage indent kissat test tissat
